### ISSUE TITLE
Can't export the model posterior to the anndata object

### ISSUE THREAD

**Issue by joaoufrj** [BayraktarLab/cell2fate#7]
Hi,

I am running cell2fate on a M1 MBP and as you know NVIDIA GPU, CUDA with Pytorch will not work in ARM Macs. I can train the model [mod.train()], the following message appears:
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs

But when I export the model posterior to the anndata object with adata = mod.export_posterior(adata), I get the following issue:

AssertionError                            Traceback (most recent call last)
Cell In[17], line 1
----> 1 adata = mod.export_posterior(adata)

File ~/opt/anaconda3/envs/cell2fate_env/lib/python3.9/site-packages/cell2fate/_cell2fate_DynamicalModel.py:290, in Cell2fate_DynamicalModel.export_posterior(self, adata, sample_kwargs, export_slot, full_velocity_posterior, normalize)
    286     sample_kwargs['batch_size'] = adata.n_obs
    288 # generate samples from posterior distributions for all parameters
    289 # and compute mean, 5%/95% quantiles and standard deviation
--> 290 self.samples = self.sample_posterior(**sample_kwargs)
    292 # export posterior distribution summary for all parameters and
    293 # annotation (model, date, var, obs and cell type names) to anndata object
    294 adata.uns[export_slot] = self._export2adata(self.samples)

File ~/opt/anaconda3/envs/cell2fate_env/lib/python3.9/site-packages/scvi/model/base/_pyromixin.py:483, in PyroSampleMixin.sample_posterior(self, num_samples, return_sites, use_gpu, batch_size, return_observed, return_samples, summary_fun)
    436 """
    437 Summarise posterior distribution.
    438 
   (...)
    480 to keep all model-specific variables in one place.
    481 """
    482 # sample using minibatches (if full data, data is moved to GPU only once anyway)
--> 483 samples = self._posterior_samples_minibatch(
    484     use_gpu=use_gpu,
    485     batch_size=batch_size,
    486     num_samples=num_samples,
    487     return_sites=return_sites,
    488     return_observed=return_observed,
    489 )
    491 param_names = list(samples.keys())
    492 results = dict()

File ~/opt/anaconda3/envs/cell2fate_env/lib/python3.9/site-packages/cell2fate/_cell2fate_DynamicalModel.py:796, in Cell2fate_DynamicalModel._posterior_samples_minibatch(self, use_gpu, batch_size, **sample_kwargs)
    779 """
    780 Temporary solution for batch sampling problem.
    781 
   (...)
    792 dictionary {variable_name: [array with samples in 0 dimension]}
    793 """
    794 samples = dict()
--> 796 _, device = parse_use_gpu_arg(use_gpu)
    798 batch_size = batch_size if batch_size is not None else settings.batch_size
    800 train_dl = AnnDataLoader(
    801     self.adata_manager, shuffle=False, batch_size=batch_size
    802 )

File ~/opt/anaconda3/envs/cell2fate_env/lib/python3.9/site-packages/scvi/model/_utils.py:40, in parse_use_gpu_arg(use_gpu, return_device)
     38     device = torch.device("cpu")
     39 elif (use_gpu is None and gpu_available) or (use_gpu is True):
---> 40     current = torch.cuda.current_device()
     41     device = torch.device(current)
     42     gpus = [current]

File ~/opt/anaconda3/envs/cell2fate_env/lib/python3.9/site-packages/torch/cuda/__init__.py:481, in current_device()
    479 def current_device() -> int:
    480     r"""Returns the index of a currently selected device."""
--> 481     _lazy_init()
    482     return torch._C._cuda_getDevice()

File ~/opt/anaconda3/envs/cell2fate_env/lib/python3.9/site-packages/torch/cuda/__init__.py:210, in _lazy_init()
    206     raise RuntimeError(
    207         "Cannot re-initialize CUDA in forked subprocess. To use CUDA with "
    208         "multiprocessing, you must use the 'spawn' start method")
    209 if not hasattr(torch._C, '_cuda_getDeviceCount'):
--> 210     raise AssertionError("Torch not compiled with CUDA enabled")
    211 if _cudart is None:
    212     raise AssertionError(
    213         "libcudart functions unavailable. It looks like you have a broken build?")

AssertionError: Torch not compiled with CUDA enabled

Looks like I could edit some of the functions to not expect the usage of CUDA, but I am not sure where that should be done. If you could please help me, I would love to be able to use this package in my data. Thanks!

**Comment by sezginerr** [comment]
Hello @joaoufrj,

Could you please try setting the `use_gpu` argument to `False` in the `sample_kwargs` as follows:

```
sample_kwarg = {"num_samples": 20, "batch_size" : 2000,
                         "use_gpu" : False, 'return_samples': True}

adata = mod.export_posterior(adata, sample_kwargs=sample_kwarg)
```

With this change, you should be able to export posteriors without using CUDA.
